<a href="https://colab.research.google.com/github/ANURADHA123-SINGH/Data-Analaytics-project-s-/blob/main/Airbnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone 'https://github.com/HarshvardhanSingh-13/Datasets'

Cloning into 'Datasets'...
remote: Enumerating objects: 347, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 347 (delta 25), reused 0 (delta 0), pack-reused 242 (from 1)
Receiving objects: 100% (347/347), 302.89 MiB | 16.28 MiB/s, done.
Resolving deltas: 100% (139/139), done.
Updating files: 100% (245/245), done.

In [2]:
import pandas as pd
df = pd.read_csv('/content/Datasets/Airbnb/airbnb.csv')

In [3]:
df.head()

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"

## 1) overall data analytics

In [4]:
df.describe()

                 id       host_id
count  1.445600e+04  1.401700e+04
mean   7.138227e+16  1.619384e+08
std    1.962072e+17  1.403407e+08
min    1.313100e+04  2.303900e+04
25%    2.047078e+07  3.603925e+07
50%    3.524320e+07  1.243490e+08
75%    4.951689e+07  2.607109e+08
max    7.017905e+17  4.758973e+08

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14456 entries, 0 to 14455
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            14456 non-null  int64
 1   name          14455 non-null  object
 2   rating        14456 non-null  object
 3   reviews       11712 non-null  object
 4   host_name     14455 non-null  object
 5   host_id       14017 non-null  float64
 6   address       14429 non-null  object
 7   features      14429 non-null  object
 8   amenities     13467 non-null  object
 9   safety_rules  14247 non-null  object
 10  hourse_rules  14247 non-null  object
 11  img_links     14429 non-null  object
 12  price         14456 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.4+ MB

In [6]:
df.isnull().sum()

id                 0
name               1
rating             0
reviews         2744
host_name          1
host_id          439
address           27
features          27
amenities        989
safety_rules     209
hourse_rules     209
img_links         27
price              0
dtype: int64

In [7]:
df[df['rating'] == 'New']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"
5,48650769,CasaMia White Suite Treehouse,New,NaN,Treehouse hosted by Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹14,729 per night"
6,50765985,Ladin Bungalow,New,NaN,Entire bungalow hosted by Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,Check out: 11:00 am,No...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹12,312 per night"
7,40947216,Lavender House,New,NaN,Treehouse hosted by Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Self check-in with building...",https://a0.muscache.com/im/pictures/97046585-1...,"₹13,655 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14440,53925646,Dome2 Rooms Dome2 in a home where you can esca...,New,1,Pension hosted by Onda,331826286.0,"Nam-myeon, Jeongseon-gun, Gangwon Province, So...","5 guests,1 bedroom,1 bathroom","Waterfront,Kitchen,Wifi,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹4,980 per night"
14441,41257160,Romantic stay at Tent galaxy villa with jacuzzi,New,1,Dome hosted by Pt. Archi,110392424.0,"Kecamatan Kuta Selatan, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 bathroom","Wifi,Free parking on premises,Private pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Self check-in with loc...",https://a0.muscache.com/im/pictures/641046c0-e...,"₹10,729 per night"
14443,621201623913222432,Kintamani Glamping Black Lava camp Potato 2,New,NaN,Private room in dome hosted by Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Fire pit,Long-te...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹3,428 per night"
14445,44045739,Tambu a mare,New,NaN,Entire home hosted by Maria,122986750.0,"Augusta, Sicilia, Italy","5 guests,1 bedroom,2 beds,1.5 bathrooms","Beach access – Beachfront,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 1:00 pm - 8:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/8cac9ffa-5...,"₹8,841 per night"
14449,640474109823176234,"Holiday home, Plemmirio",New,NaN,Entire home hosted by Daphne Belvilla,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 8:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹20,311 per night"

In [8]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Dome hosted by Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,288 per night"
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Tent hosted by Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/5ba944b2-b...,"₹15,200 per night"
14453,32977697,Paradise Eco Hub,4.67,3,Private room in dome hosted by Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/1f442c84-4...,"₹9,103 per night"
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Dome hosted by Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",https://a0.muscache.com/im/pictures/105116799/...,"₹42,262 per night"
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Dome hosted by Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/9b04ee4c-c...,"₹9,909 per night"

In [9]:
display(df[df.isnull().any(axis =1)])

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"
5,48650769,CasaMia White Suite Treehouse,New,NaN,Treehouse hosted by Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹14,729 per night"
6,50765985,Ladin Bungalow,New,NaN,Entire bungalow hosted by Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,Check out: 11:00 am,No...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹12,312 per night"
7,40947216,Lavender House,New,NaN,Treehouse hosted by Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Self check-in with building...",https://a0.muscache.com/im/pictures/97046585-1...,"₹13,655 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14436,621278037552014887,Kintamani Glamping Black Lava Camp Potato 3,New,NaN,Private room in dome hosted by Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Lake view,Mountain view,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹3,490 per night"
14439,624406715458043020,Kintamani Glamping Black Lava Camp Onion 3,New,NaN,Private room in dome hosted by Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Long-term stays ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹3,864 per night"
14443,621201623913222432,Kintamani Glamping Black Lava camp Potato 2,New,NaN,Private room in dome hosted by Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Fire pit,Long-te...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹3,428 per night"
14445,44045739,Tambu a mare,New,NaN,Entire home hosted by Maria,122986750.0,"Augusta, Sicilia, Italy","5 guests,1 bedroom,2 beds,1.5 bathrooms","Beach access – Beachfront,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 1:00 pm - 8:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/8cac9ffa-5...,"₹8,841 per night"
14449,640474109823176234,"Holiday home, Plemmirio",New,NaN,Entire home hosted by Daphne Belvilla,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 8:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹20,311 per night"

In [10]:
df['amenities'].mode()[0]

'Long-term stays allowed,Unavailable: Carbon monoxide alarmCarbon monoxide alarm,Unavailable: Smoke alarmSmoke alarm'

In [11]:
df['hourse_rules'].mode()[0]

'Check-in: After 3:00 pm'

In [12]:
df.dropna(subset=['reviews'],inplace=True)

In [13]:
df.isnull().sum()

id                0
name              0
rating            0
reviews           0
host_name         0
host_id         207
address           0
features          0
amenities       716
safety_rules     95
hourse_rules     95
img_links         0
price             0
dtype: int64

In [14]:
df['host_id'].mode()

0    157378426.0
Name: host_id, dtype: float64

In [15]:
df.drop_duplicates(subset=['id'],inplace=True)

In [16]:
df.isnull().sum()

id                0
name              0
rating            0
reviews           0
host_name         0
host_id         169
address           0
features          0
amenities       670
safety_rules     92
hourse_rules     92
img_links         0
price             0
dtype: int64

In [17]:
df[df['id'] == 31378793]['host_name']

861    Designer villa with private vineyard, sommelier
Name: host_name, dtype: object

In [18]:
df[df['host_id'].isnull()]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
725,588250406117563784,Maison Cardinal Furstemberg,5.0,6,"Luxury stay in Paris, Île-de-France, France",NaN,"Paris, Île-de-France, France","7 guests,3 bedrooms,3 beds,4 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 5:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹2,38,171 per night"
801,35839817,Icaria,5.0,3,"Luxury stay in Cape Town, Western Cape, South ...",NaN,"Cape Town, Western Cape, South Africa","10 guests,5 bedrooms,5 beds,5 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/5bdf180f-a...,"₹84,468 per night"
861,31378793,Villa Grenache,New,1,"Designer villa with private vineyard, sommelier",NaN,"Cape Town, Western Cape, South Africa","10 guests,5 bedrooms,5 beds,5 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/dfe31a03-b...,"₹44,239 per night"
2337,20473398,Villa Sawarin,New,1,"Luxury stay in Thalang, Phuket, Thailand",NaN,"Thalang, Phuket, Thailand","16 guests,9 bedrooms,10 beds,10 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 3:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/009f1d32-c...,"₹3,15,089 per night"
2339,20470768,Samujana Twenty-Four,New,1,Modernism and vintage Thai art on coastal hill...,NaN,"Koh Samui, Suratthani, Thailand","16 guests,8 bedrooms,8 beds,10 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 3:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/949f5b43-9...,"₹2,73,673 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12277,26202362,Villa Ferraia,4.87,15,Ultra private hilltop retreat near Monticiano,NaN,"Tocchi, Siena, Italy","16 guests,14 bedrooms,14 beds,15.5 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 4:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/b10bcc29-2...,"₹3,36,853 per night"
12286,26202400,Sole del Chianti,4.89,19,"Luxury stay in Tavarnelle Val di Pesa, Florenc...",NaN,"Tavarnelle Val di Pesa, Florence, Italy","16 guests,10 bedrooms,11 beds,11 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 6:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/153dc0ce-5...,"₹1,19,086 per night"
12301,20473328,Il Parco del Principe,New,2,Neo-Gothic garden villa near Chiusi,NaN,"Chiusi, Siena, Italy","16 guests,8 bedrooms,9 beds,8.5 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 4:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/5db05d12-4...,"₹3,28,914 per night"
12348,20472010,Casa Lazzari,4.82,11,Casa Lazzari,NaN,"Umbertide, Perugia, Italy","12 guests,6 bedrooms,6 beds,8 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 5:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/6d8db649-7...,"₹80,518 per night"
12394,20204291,Chateau d'Azur,New,1,Chateau d'Azur - 15Br - Sleeps 30,NaN,"Frejus, Provence-Alpes-Côte d'Azur, France","16 guests,15 bedrooms,17 beds,14 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 4:00 pm,Check out: 10:00 am,No...",https://a0.muscache.com/im/pictures/5c7acb18-f...,"₹6,85,377 per night"

In [19]:
display(df[df.isnull().any(axis = 1)])

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
26,625932329535277910,sapanca Bungalife M,4.6,5,Treehouse hosted by Kemal,457654417.0,"Memnuniye, Sakarya, Turkey","7 guests,3 bedrooms,4 beds,2 bathrooms","Kitchen,Free residential garage on premises,Pr...",NaN,NaN,https://a0.muscache.com/im/pictures/944c4e82-c...,"₹15,052 per night"
132,33343364,Glamping Forest Edge #No3,New,1,Room in bed and breakfast hosted by Rožle,228484488.0,"Radomlje, Kamnik, Slovenia","3 guests,1 bedroom,2 beds,4 shared bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 4:00 pm - 8:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹6,669 per night"
136,33343138,Glamping Forest Edge #No2,New,1,Room in bed and breakfast hosted by Rožle,228484488.0,"Radomlje, Kamnik, Slovenia","3 guests,1 bedroom,2 beds,4 shared bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 4:00 pm - 8:00 pm,Self check-in with...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹8,336 per night"
241,33325892,Mao Mao surf (Jungle hut 3: Drunk parrot),4.93,27,Room in bed and breakfast hosted by Marco,13119109.0,"General Luna, Surigao del Norte, Philippines","2 guests,1 bedroom,1 bed,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 2:00 pm - 6:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/50fc4b29-6...,"₹4,005 per night"
261,586461707995407164,A Frame Tiny Cabin with swimming pool.,New,1,Private room in bed and breakfast hosted by Fr...,428123005.0,"Moshi Urban, Kilimanjaro Region, Tanzania","2 guests,1 bedroom,1 bed,1 private bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...",NaN,NaN,https://a0.muscache.com/im/pictures/6770d413-d...,"₹7,191 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14119,26155377,IVORY STD Double (Clean room & Care your holiday),4.74,38,Room in hostel hosted by Ivory,152784753.0,"Ao Nang, Krabi, Thailand","2 guests,Studio,1 bed,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 7:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/210060b7-3...,"₹2,264 per night"
14142,33429446,"lovely rest,free island hopping",4.71,14,Room in resort hosted by Chan,156727997.0,"Langkawi, Kedah, Malaysia","4 guests,1 bedroom,3 beds,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 12:00 am,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/75c685d6-0...,"₹3,302 per night"
14227,54075486,"PIR-Panjal Luxury Glamping Dome in Sethan, Manali",New,2,Dome hosted by Dipshikha,370696228.0,"Manali, Himachal Pradesh, India","4 guests,1 bedroom,4 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Dedicat...",NaN,NaN,https://a0.muscache.com/im/pictures/a250ff2d-a...,"₹6,790 per night"
14396,53140890,Richland Bali - Private Glamping by The Lake 02,New,2,Private room in dome hosted by Raka,420521923.0,"Kecamatan Baturiti, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 private bathroom","Lake access,Wifi,Dedicated workspace,Free park...",NaN,NaN,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹2,759 per night"
14424,22285856,LA CASA HIBISCUS,4.88,56,Room in nature lodge hosted by Chrystel,55358262.0,"Trou-aux-Biches, Pamplemousses District, Mauri...","2 guests,1 bedroom,2 beds,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 2:00 pm - 11:00 pm,Check out: 9:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,168 per night"

In [20]:
df.isnull().sum()

id                0
name              0
rating            0
reviews           0
host_name         0
host_id         169
address           0
features          0
amenities       670
safety_rules     92
hourse_rules     92
img_links         0
price             0
dtype: int64

In [21]:
df.dropna(subset=['host_id'],inplace= True)

In [22]:
df['amenities'].fillna('NO amnenities',inplace=True)

/tmp/ipykernel_338/482103728.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['amenities'].fillna('NO amnenities',inplace=True)

In [23]:
df.isnull().sum()

id               0
name             0
rating           0
reviews          0
host_name        0
host_id          0
address          0
features         0
amenities        0
safety_rules    92
hourse_rules    92
img_links        0
price            0
dtype: int64

In [24]:
df['hourse_rules']

0        Check-in: Flexible,Check out: 12:00 pm,Pets ar...
2        Check-in: After 1:00 pm,Check out: 12:00 pm,Se...
3        Check-in: After 2:00 pm,Check out: 12:00 pm,No...
9               Check-in: After 3:00 pm,No smoking,No pets
10       Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...
                               ...
14451    Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...
14452    Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...
14453                              Check-in: After 3:00 pm
14454    Check-in: Flexible,Check out: 12:00 pm,No pets...
14455    Check-in: After 4:00 pm,Check out: 11:00 am,Se...
Name: hourse_rules, Length: 10913, dtype: object

In [25]:
df['safety_rules'].fillna('No Safety Rules',inplace = True)

/tmp/ipykernel_338/3132175608.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['safety_rules'].fillna('No Safety Rules',inplace = True)

In [26]:
df['hourse_rules'].fillna('Check-in:Flexible,Check-out: 12:00 pm',inplace=True)

In [27]:
df.isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
host_id         0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
img_links       0
price           0
dtype: int64

#2) Column wise cleaning

In [28]:
df.columns

Index(['id', 'name', 'rating', 'reviews', 'host_name', 'host_id', 'address',
       'features', 'amenities', 'safety_rules', 'hourse_rules', 'img_links',
       'price'],
      dtype='object')

In [29]:
df['id']

0        49849504
2        50699164
3        49871422
9        42075682
10       50425621
           ...
14451    44697740
14452    29975283
14453    32977697
14454     8006146
14455    40547903
Name: id, Length: 10913, dtype: int64

In [30]:
df['name']

0                                           Perla bungalov
2                                        cottages sataplia
3                              Sapanca Breathable Bungalow
9                          The Cottage, Private Pool Villa
10       A private pension hut on the hillside of Sokli...
                               ...
14451              Brown Dome House No. 3, full of healing
14452         Bubble Hotel Ubud with Bathtub under the Sky
14453                                     Paradise Eco Hub
14454       WisDOME - Mentigi Bay Village - Gilis - Lombok
14455     Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]
Name: name, Length: 10913, dtype: object

In [31]:
df['rating'] = df['rating'].str.replace("New",'0.0')

In [32]:
df['rating']=df['rating'].astype(float)

In [33]:
df.describe()

                 id        rating       host_id
count  1.091300e+04  10913.000000  1.091300e+04
mean   5.189309e+16      4.012812  1.488154e+08
std    1.700420e+17      1.845709  1.343755e+08
min    1.313100e+04      0.000000  2.303900e+04
25%    1.806686e+07      4.650000  3.138719e+07
50%    3.276592e+07      4.850000  1.075332e+08
75%    4.783970e+07      4.960000  2.375400e+08
max    6.895649e+17      5.000000  4.721663e+08

In [34]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.00,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Entire home hosted by Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedrooms,6 beds,3 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets",https://a0.muscache.com/im/pictures/42d26843-4...,"₹30,486 per night"
10,50425621,A private pension hut on the hillside of Sokli...,4.97,77,Farm stay hosted by 동현,81358542.0,"Sanoe-myeon, Boeun-gun, North Chungcheong Prov...","4 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Free on-street parking,C...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹9,052 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Dome hosted by Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,288 per night"
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Tent hosted by Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/5ba944b2-b...,"₹15,200 per night"
14453,32977697,Paradise Eco Hub,4.67,3,Private room in dome hosted by Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/1f442c84-4...,"₹9,103 per night"
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Dome hosted by Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",https://a0.muscache.com/im/pictures/105116799/...,"₹42,262 per night"
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Dome hosted by Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/9b04ee4c-c...,"₹9,909 per night"

In [35]:
df['reviews'] = df['reviews'].str.replace(",", '')

In [36]:
df['reviews'] = df['reviews'].astype(int)

In [37]:
df['host_name'] = df['host_name'].str.split('by').str[1]

In [38]:
df['host_name'] = df['host_name'].str.strip()

In [39]:
df['host_id'] = df['host_id'].astype(object)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10913 entries, 0 to 14455
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10913 non-null  int64
 1   name          10913 non-null  object
 2   rating        10913 non-null  float64
 3   reviews       10913 non-null  int64
 4   host_name     10913 non-null  object
 5   host_id       10913 non-null  object
 6   address       10913 non-null  object
 7   features      10913 non-null  object
 8   amenities     10913 non-null  object
 9   safety_rules  10913 non-null  object
 10  hourse_rules  10913 non-null  object
 11  img_links     10913 non-null  object
 12  price         10913 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 1.2+ MB

In [41]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.00,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedrooms,6 beds,3 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets",https://a0.muscache.com/im/pictures/42d26843-4...,"₹30,486 per night"
10,50425621,A private pension hut on the hillside of Sokli...,4.97,77,동현,81358542.0,"Sanoe-myeon, Boeun-gun, North Chungcheong Prov...","4 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Free on-street parking,C...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹9,052 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,288 per night"
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/5ba944b2-b...,"₹15,200 per night"
14453,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/1f442c84-4...,"₹9,103 per night"
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",https://a0.muscache.com/im/pictures/105116799/...,"₹42,262 per night"
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/9b04ee4c-c...,"₹9,909 per night"

In [42]:
df.groupby('host_id')['host_name'].count().sort_values(ascending= False)

host_id
157378426.0    20
233211645.0    13
105199196.0    11
7455203.0      10
85667941.0      9
               ..
59652772.0      1
59669198.0      1
59687931.0      1
59689593.0      1
59321932.0      1
Name: host_name, Length: 9136, dtype: int64

In [43]:
df['country']=df['address'].str.split(',').str[-1].str.split()

In [44]:
df[['host_id','host_name']].value_counts()

host_id      host_name
157378426.0  Shanu              20
233211645.0  HotelSnow          13
105199196.0  Paolo              11
7455203.0    Alessandro&Anna    10
85667941.0   Temuri              9
                                ..
59652772.0   Katja               1
59669198.0   Bayu & Wayana       1
59687931.0   Evgeni              1
59689593.0   Kamolnate           1
59321932.0   Margarita           1
Name: count, Length: 9136, dtype: int64

In [45]:
df['amenities'].str.split(',').str[0]

0        Mountain view
2        Mountain view
3        Mountain view
9              Kitchen
10       Mountain view
             ...
14451          Kitchen
14452             Wifi
14453             Wifi
14454          Kitchen
14455         Sea view
Name: amenities, Length: 10913, dtype: object

In [46]:
df['hourse_rules']

0        Check-in: Flexible,Check out: 12:00 pm,Pets ar...
2        Check-in: After 1:00 pm,Check out: 12:00 pm,Se...
3        Check-in: After 2:00 pm,Check out: 12:00 pm,No...
9               Check-in: After 3:00 pm,No smoking,No pets
10       Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...
                               ...
14451    Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...
14452    Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...
14453                              Check-in: After 3:00 pm
14454    Check-in: Flexible,Check out: 12:00 pm,No pets...
14455    Check-in: After 4:00 pm,Check out: 11:00 am,Se...
Name: hourse_rules, Length: 10913, dtype: object

In [47]:
df['Check-In'] = df['hourse_rules'].str.split(',').str[0].str.split('in:').str[1].str.strip()

In [48]:
df['Check-Out'] = df['hourse_rules'].str.split(',').str[1].str.split('out:').str[1].str.strip().fillna('12:00 pm')

In [49]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price,country,Check-In,Check-Out
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night",[Turkey],Flexible,12:00 pm
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night",[Georgia],After 1:00 pm,12:00 pm
3,49871422,Sapanca Breathable Bungalow,5.00,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night",[Turkey],After 2:00 pm,12:00 pm
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedrooms,6 beds,3 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets",https://a0.muscache.com/im/pictures/42d26843-4...,"₹30,486 per night",[Thailand],After 3:00 pm,12:00 pm
10,50425621,A private pension hut on the hillside of Sokli...,4.97,77,동현,81358542.0,"Sanoe-myeon, Boeun-gun, North Chungcheong Prov...","4 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Free on-street parking,C...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹9,052 per night","[South, Korea]",3:00 pm - 9:00 pm,11:00 am
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,288 per night","[South, Korea]",3:00 pm - 11:00 pm,11:00 am
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/5ba944b2-b...,"₹15,200 per night",[Indonesia],3:00 pm - 10:00 pm,12:00 pm
14453,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/1f442c84-4...,"₹9,103 per night",[Uganda],After 3:00 pm,12:00 pm
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",https://a0.muscache.com/im/pictures/105116799/...,"₹42,262 per night",[Indonesia],Flexible,12:00 pm
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/9b04ee4c-c...,"₹9,909 per night",[Japan],After 4:00 pm,11:00 am

In [50]:
del df['img_links']

In [51]:
df.head(5)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,price,country,Check-In,Check-Out
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...","₹8,078 per night",[Turkey],Flexible,12:00 pm
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...","₹5,991 per night",[Georgia],After 1:00 pm,12:00 pm
3,49871422,Sapanca Breathable Bungalow,5.00,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...","₹11,339 per night",[Turkey],After 2:00 pm,12:00 pm
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedrooms,6 beds,3 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets","₹30,486 per night",[Thailand],After 3:00 pm,12:00 pm
10,50425621,A private pension hut on the hillside of Sokli...,4.97,77,동현,81358542.0,"Sanoe-myeon, Boeun-gun, North Chungcheong Prov...","4 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Free on-street parking,C...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...","₹9,052 per night","[South, Korea]",3:00 pm - 9:00 pm,11:00 am

In [52]:
df['features'].str.split(',').str[0].value_counts()

features
2 guests     3213
4 guests     2298
6 guests     1270
3 guests     1109
5 guests      647
8 guests      618
16 guests     403
10 guests     356
12 guests     245
7 guests      234
9 guests      183
1 guest        94
14 guests      92
15 guests      81
11 guests      39
13 guests      31
Name: count, dtype: int64

In [53]:
df['No_of_guest']=df['features'].str.split(',').str[0].str.split().str[0].astype(int)

In [54]:
df['price'] = df['price'].str.split().str[0].str.split('₹').str[1].str.replace(',','').str.strip().astype(int)

In [55]:
df['features']=df['features'].str.replace('bedroomss','bedroom').str.replace('bedrooms','bedroom').str.replace('beds','bed').str.replace('bathrooms','bathroom')

In [56]:
df['features']

0                2 guests,2 bedroom,1 bed,1 bathroom
2                4 guests,1 bedroom,3 bed,1 bathroom
3                4 guests,1 bedroom,2 bed,1 bathroom
9               10 guests,4 bedroom,6 bed,3 bathroom
10               4 guests,1 bedroom,1 bed,1 bathroom
                            ...
14451                            4 guests,8 bathroom
14452      2 guests,1 bedroom,1 bed,Toilet with sink
14453    2 guests,1 bedroom,2 bed,1 private bathroom
14454          8 guests,2 bedroom,4 bed,2.5 bathroom
14455            5 guests,1 bedroom,2 bed,1 bathroom
Name: features, Length: 10913, dtype: object

In [57]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,price,country,Check-In,Check-Out,No_of_guest
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedroom,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",8078,[Turkey],Flexible,12:00 pm,2
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 bed,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",5991,[Georgia],After 1:00 pm,12:00 pm,4
3,49871422,Sapanca Breathable Bungalow,5.00,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 bed,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",11339,[Turkey],After 2:00 pm,12:00 pm,4
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedroom,6 bed,3 bathroom","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets",30486,[Thailand],After 3:00 pm,12:00 pm,10
10,50425621,A private pension hut on the hillside of Sokli...,4.97,77,동현,81358542.0,"Sanoe-myeon, Boeun-gun, North Chungcheong Prov...","4 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Free on-street parking,C...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: 3:00 pm - 9:00 pm,Check out: 11:00 a...",9052,"[South, Korea]",3:00 pm - 9:00 pm,11:00 am,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathroom","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",4288,"[South, Korea]",3:00 pm - 11:00 pm,11:00 am,4
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",15200,[Indonesia],3:00 pm - 10:00 pm,12:00 pm,2
14453,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 bed,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,9103,[Uganda],After 3:00 pm,12:00 pm,2
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedroom,4 bed,2.5 bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",42262,[Indonesia],Flexible,12:00 pm,8
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 bed,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",9909,[Japan],After 4:00 pm,11:00 am,5

## Questions for EDA:
# 1)What are the most popular listing types based on ratings or number of reviews?
# 2) Which countries have the most Airbnb listings?
# 3)How does the number of reviews relate to the rating of a listing?
#4) What are the most common amenities offered in the listings?
#5) Is there a relationship between the price of a listing and the number of guests it can accommodate?
#6) What are the typical check-in and check-out times?
#7) Are there any patterns in safety rules or house rules across different locations or listing types?
#8) How are the prices distributed across different countries or regions?
#9)Can we identify any trends or patterns in the features offered (number of bedrooms, beds, bathrooms)?
#10)What is the distribution of ratings? Are there many new listings with no ratings?

In [58]:
# Install ydata-profiling
!pip install ydata-profiling -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 19.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 72.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 5.1 MB/s eta 0:00:00

In [ ]:
# Generate the profiling report
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Titanic Dataset Profiling Report")
profile
# Display the report in the notebook
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]